### ISSUE TITLE
#FeatureRequest Tray Icon support

### ISSUE THREAD

**Issue by SophiePie** [tomatoers/tomato#48]
First off, great app. Really useful!
![screenshot from 2018-06-15 00 43 38](https://user-images.githubusercontent.com/38818135/41443503-45ff2b14-7035-11e8-8b35-5d7aa4a5c0d4.png)

I'd like to be able to see the progress in the form of a tray-icon instead of the dock since it's not visible when any app is fullscreen. Thank you

**Comment by cassidyjames** [comment]
Considering that this is not a supported feature on elementary OS anymore, I don't think it's something we're going to devote resources to.
