### ISSUE TITLE
fails on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by invegat** [tomatoers/tomato#51]
E: The repository 'http://ppa.launchpad.net/tomato-team/tomato-stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by cassidyjames** [comment]
The PPA does not exist for 18.04. Considering we are targeting elementary OS, the recommended method for installation is via AppCenter once it has been updated.

**Comment by invegat** [comment]
chrome "1 min 1 sec timer"  works for as timer, don't need any app
