### ISSUE TITLE
Disappeared?

### ISSUE THREAD

**Issue by wout** [tomatoers/tomato#53]
I'd love to use this app but I can't find it in Juno's AppCentre. Did you pull it?

**Comment by ryonakano** [comment]
Unfortunately it's not released for Juno yet, please see #50 (and this is duplicated)

**Comment by megatux** [comment]
I'm a member of "tomatoers" that cassidyjames created for this. Still can't close this issue :man_shrugging:. @luizaugustomm could you add the repo to that org? (https://github.com/tomatoers)

**Comment by luizaugustomm** [comment]
Sorry for the delay, @megatux. I had transferred the repository to Cassidy instead. But the Tomatoers own Tomato now.

By the way, I'm very happy you are putting some effort to keep Tomato alive. :)

**Comment by cassidyjames** [comment]
Considering this as a dupe of #50
